# Generated by Django 2.2.7 on 2019-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profilePictures/default.jpg', upload_to='profilePictures'),
        ),
    ]
