# Generated by Django 2.2.7 on 2019-11-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191116_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secretCode',
            field=models.CharField(max_length=32),
        ),
    ]
