# Generated by Django 2.2.7 on 2019-11-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191116_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='secretCode',
            new_name='secretKey',
        ),
    ]
