# Generated by Django 2.2.7 on 2019-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191114_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expeditionLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='expeditionWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='gameMode',
            field=models.CharField(default='normal', max_length=11),
        ),
    ]
