# Generated by Django 2.2.7 on 2019-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191115_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameMode',
            field=models.CharField(default='Normal', max_length=11),
        ),
    ]
