# Generated by Django 2.2.7 on 2019-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20191115_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.CharField(default='Nothing', max_length=100),
            preserve_default=False,
        ),
    ]
