# Generated by Django 2.2.7 on 2019-11-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20191121_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expeditionLosses',
        ),
        migrations.RemoveField(
            model_name='card',
            name='normalLosses',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='region',
            name='expeditionLosses',
        ),
        migrations.RemoveField(
            model_name='region',
            name='normalLosses',
        ),
    ]
