# Generated by Django 2.2.7 on 2019-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20191121_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='regions',
            field=models.CharField(default='Demacia', max_length=100),
            preserve_default=False,
        ),
    ]
